### ISSUE TITLE
List connected, but not activated(?) monitors?

### ISSUE THREAD

**Issue by AkkermanD** [dzfranklin/xrandr-rs#6]
Hey! Thanks for the crate :)
I know nothing about xrandr, but I'm looking to implement toy-project to automatically activate/deactivate my external monitors when I'm connecting/disconnecting them.
I noticed that when I'm just pluggin in the external monitor it appears in the xrandr output:
```
HDMI-1 connected (normal left inverted right x axis y axis)
   1680x1050     59.88 +
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
````
This shows even if monitor is not "switched off" by button. But it is not listed in the `XHandle::open().unwrap().monitors()`. Is it possible to list the monitors that are not "activated" somehow?

**Comment by dzfranklin** [comment]
I'm not actively working with this crate, so you'd have to do this yourself. I have no idea how xrandr works either, I built this for a toy.

But: `.monitors` ends up calling a function called `XRRGetMonitors`

```rust
            unsafe { xrandr::XRRGetMonitors(self.sys.as_ptr(), self.root(), 0, &mut count) };
```
(In [`lib.rs:120`](https://github.com/danielzfranklin/xrandr-rs/blob/main/src/lib.rs#L120))

And if you look into the [autogenerated docs](https://doc.servo.org/x11/xrandr/fn.XRRGetMonitors.html) the third parameter is called `get_active`.

So what I would do in your position is try forking this crate and flipping that parameter from `0` to `1`. If that works you could file a PR that exposes some nice API, which I'd be happy to merge.

Good luck! Feel free to ask more questions, I'll see if I remember anything relevant.

**Comment by AkkermanD** [comment]
Thanks, Daniel! Will look into, not sure when, but I'll get to it :)
